profiles:  dev_environment
server:
  port: 9005
  servlet:
    context-path: /attendance
spring:
  datasource:
    url: @datasource.url@
    username: @datasource.username@
    password: @datasource.password@
    driver-class-name: org.postgresql.Driver
  application:
    name: data-server
  jpa:
    generate-ddl: true
    properties:
      format_sql: true
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect
  thymeleaf:
    cache: false
    cache-period: 0
  redis:
    host: @redis.url@
    port: 6379
    password: @redis.password@
  fluentd:
    host: @fluentd.url@
    port: @fluentd.port@
    label: @label@
#  rabbitmq:
#    host: @rabbitmq.host@
#    port: @rabbitmq.port@
#    username: @rabbitmq.username@
#    password: @rabbitmq.password@
#    publisher-confirms: true
#    virtual-host: /
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
logging:
  level:
    com:
      yulintu: DEBUG
upload:
  path: C:/upload #将此路径用iis配置发布
  type: local
  accessUrlRoot: http://192.168.0.127:9000/
  tags:
    - idCard
    - prove
    - purchaseContract
    - contract
    - logo
